version: '3.9'

services:
  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${PDB_USER}
      - POSTGRES_PASSWORD=${PDB_PASSWORD}
      - POSTGRES_DB=${PDB_NAME}
      - POSTGRES_PORT=${PDB_PORT}
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - client_manager_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PDB_USER} -d ${PDB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5


  migrate:
    image: migrate/migrate
    networks:
      - client_manager_network
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres-db
    command: ["-path", "/migrations", "-database" ,"postgres://${PDB_USER}:${PDB_PASSWORD}@postgres:${PDB_PORT}/${PDB_NAME}?sslmode=disable","up"]

  userservice:
    container_name: auth
    build: .
    ports:
      - "8080:8080"
    networks:
      - client_manager_network
    depends_on:
      postgres-db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

networks:
  client_manager_network:
    external: true


volumes:
  db:
    driver: local
